<?php
/**
 * Created by PhpStorm.
 * User: lerny
 * Date: 13/12/15
 * Time: 01:13 PM
 */
class CoreConfig extends CoreSingleton
{
    private $alreadyInit = false;
    private $config = array();
    /**
     * @return CoreConfig
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }
    /**
     * @return CoreConfig
     */
    public static function getConfig($only_public = false) {
        $config = self::getInstance();
        if(!$config->isAlreadyInit()) {
            $config->init($only_public);
        }
        return $config;
    }
    /**
     * @return boolean
     */
    public function isAlreadyInit()
    {
        return $this->alreadyInit;
    }
    /**
     * @return array
     */
    public function getData()
    {
        return $this->config;
    }
    public function init($only_public = false) {
        $this->alreadyInit = true;
        $db = CoreDb::getInstance();
        $result = $db->query("SELECT * FROM config");
        foreach($result as $value) {
            $pasar = true;
            if($only_public && $value["is_only_private"] == "1") {
                $pasar = false;
            }
            if($pasar) {
                $this->config[$value["etiqueta"]] = $value["valor"];
            }
        }
        $this->config["tipo_user"] = array(
            "admin" => _("Admin"),
            "usuario" => _("Usuario")
        );
        $this->config["estado_user"] = array(
            "0" => _("Inactivo"),
            "1" => _("Activo")
        );
        $this->config["tipo_boletin"] = array(
            "m" => _("Manual"),
            "p" => _("Programado")
        );
        $this->config["from_boletin"] = array(
            "estudiantes" => _("Estudiantes"),
            "supervisores" => _("Supervisores")
        );
        $urls = array();
        ModuleConfiguracionConfig::getUrls($urls);
        $this->config["urls"] = json_encode($urls);
    }
}